name: docker-build-and-push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKENN }}
      -
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and package with Maven
        run: mvn clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/*.jar
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: savokostadinov/devopsproject:latest
